In [2]:
from pathlib import Path

import pandas as pd
import numpy as np
from PIL import Image

import torch
from torch import nn
from torch.utils.data import Dataset, DataLoader
from k_means_constrained import KMeansConstrained

from sklearn.model_selection import train_test_split
from transformers import AutoImageProcessor, AutoModelForImageClassification
from tqdm.auto import tqdm

#sns.set_theme(style="whitegrid")
pd.set_option("display.max_columns", None)

# Find the project root
PROJECT_ROOT = Path.cwd().parent

DATA_DIR = PROJECT_ROOT / "geo_dataset"
TRAIN_DIR = DATA_DIR / "train"
HOLDOUT_DIR = DATA_DIR / "holdout_public"
LABELS_PATH = DATA_DIR / "train_labels.csv"

/home/utn/poli22wo/miniconda3/envs/dl/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [3]:
OUTPUT_DIR = PROJECT_ROOT / "outputs" / "high_resolution_384"
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

best_model_path = OUTPUT_DIR / "best_model.pt"
checkpoint_path = OUTPUT_DIR / "training_checkpoint.pt"
history_path = OUTPUT_DIR / "history.csv"

In [5]:
df = pd.read_csv(LABELS_PATH)

print(df.shape)
display(df.head())

(11758, 5)

,filename,country,iso,lat,lng
0,1fcb4a43864244259b7d8f4a00f1e475.jpg,Turkey,TR,40.112290,38.304629
1,742f45b0211c44ffb19ad84931ea519c.jpg,France,FR,48.094103,-1.994316
2,152a13ef249d4efa95c51ed93f026284.jpg,Turkey,TR,41.324741,27.961821
3,81ce4a88bff14fef8420bca42019b12b.jpg,France,FR,47.585855,-2.971004
4,6fbcfe523e1349759e6060d632d52e54.jpg,United_Kingdom,GB,55.698094,-4.305315

In [6]:
countries = sorted(
    df["country"].unique()
)

country_to_index = {
    country: index
    for index, country in enumerate(countries)
}

index_to_country = {
    index: country
    for country, index in country_to_index.items()
}

df["country_index"] = df["country"].map(
    country_to_index
)

NUMBER_OF_COUNTRIES = len(countries)

print(country_to_index)

{'Belarus': 0, 'Finland': 1, 'France': 2, 'Germany': 3, 'Iceland': 4, 'Italy': 5, 'Norway': 6, 'Poland': 7, 'Spain': 8, 'Sweden': 9, 'Turkey': 10, 'United_Kingdom': 11}

Validation Split

In [7]:
train_df, val_df = train_test_split(
    df,
    test_size=0.2,
    random_state=42,
    stratify=df["country"],
)

print("Training images:", len(train_df))
print("Validation images:", len(val_df))

Training images: 9406
Validation images: 2352

In [8]:
CELLS_PER_COUNTRY = 8

NUMBER_OF_CELLS = (
    NUMBER_OF_COUNTRIES
    * CELLS_PER_COUNTRY
)

train_df = train_df.copy()
val_df = val_df.copy()

train_df["cell_index"] = -1
val_df["cell_index"] = -1

cell_centres = np.zeros(
    (NUMBER_OF_CELLS, 2),
    dtype=np.float32,
)

cell_to_country = np.zeros(
    NUMBER_OF_CELLS,
    dtype=np.int64,
)

country_constrained_models = {}
country_longitude_scales = {}

Creating balanced geographic cells inside each country

In [9]:
for country, country_index in country_to_index.items():

    train_mask = (
        train_df["country"] == country
    )

    val_mask = (
        val_df["country"] == country
    )

    country_train_coordinates = (
        train_df.loc[
            train_mask,
            ["lat", "lng"],
        ]
        .to_numpy(dtype=np.float32)
    )

    country_val_coordinates = (
        val_df.loc[
            val_mask,
            ["lat", "lng"],
        ]
        .to_numpy(dtype=np.float32)
    )

    # Correct longitude distances for latitude
    mean_latitude = np.mean(
        country_train_coordinates[:, 0]
    )

    longitude_scale = np.cos(
        np.radians(mean_latitude)
    )

    country_train_projected = (
        country_train_coordinates.copy()
    )

    country_val_projected = (
        country_val_coordinates.copy()
    )

    country_train_projected[:, 1] *= (
        longitude_scale
    )

    country_val_projected[:, 1] *= (
        longitude_scale
    )

    number_of_country_images = len(
        country_train_coordinates
    )

    minimum_cell_size = (
        number_of_country_images
        // CELLS_PER_COUNTRY
    )

    maximum_cell_size = int(
        np.ceil(
            number_of_country_images
            / CELLS_PER_COUNTRY
        )
    )

    constrained_kmeans = KMeansConstrained(
        n_clusters=CELLS_PER_COUNTRY,
        size_min=minimum_cell_size,
        size_max=maximum_cell_size,
        random_state=42,
        n_init=10,
        max_iter=100,
    )

    local_train_cells = (
        constrained_kmeans.fit_predict(
            country_train_projected
        )
    )

    # Assign each validation image independently
    # to its nearest learned centre.
    projected_centres = (
        constrained_kmeans.cluster_centers_
    )

    validation_distances = (
        (
            country_val_projected[:, None, :]
            - projected_centres[None, :, :]
        )
        ** 2
    ).sum(axis=2)

    local_val_cells = (
        validation_distances.argmin(axis=1)
    )

    first_cell = (
        country_index
        * CELLS_PER_COUNTRY
    )

    last_cell = (
        first_cell
        + CELLS_PER_COUNTRY
    )

    train_df.loc[
        train_mask,
        "cell_index",
    ] = (
        first_cell
        + local_train_cells
    )

    val_df.loc[
        val_mask,
        "cell_index",
    ] = (
        first_cell
        + local_val_cells
    )

    # Calculate centres using the original
    # latitude and longitude coordinates.
    for local_cell in range(
        CELLS_PER_COUNTRY
    ):

        global_cell = (
            first_cell + local_cell
        )

        assigned_coordinates = (
            country_train_coordinates[
                local_train_cells
                == local_cell
            ]
        )

        cell_centres[
            global_cell
        ] = assigned_coordinates.mean(
            axis=0
        )

    cell_to_country[
        first_cell:last_cell
    ] = country_index

    country_constrained_models[
        country
    ] = constrained_kmeans

    country_longitude_scales[
        country
    ] = longitude_scale

In [10]:
train_df["cell_index"] = (
    train_df["cell_index"].astype(int)
)

val_df["cell_index"] = (
    val_df["cell_index"].astype(int)
)

In [11]:
for country in countries:

    country_counts = (
        train_df.loc[
            train_df["country"] == country,
            "cell_index",
        ]
        .value_counts()
        .sort_index()
    )

    print(
        f"{country}: "
        f"min={country_counts.min()}, "
        f"max={country_counts.max()}, "
        f"total={country_counts.sum()}"
    )

    assert (
        country_counts.max()
        - country_counts.min()
        <= 1
    )

Belarus: min=86, max=87, total=691
Finland: min=100, max=100, total=800
France: min=100, max=100, total=800
Germany: min=100, max=100, total=800
Iceland: min=96, max=96, total=768
Italy: min=100, max=100, total=800
Norway: min=100, max=100, total=800
Poland: min=93, max=94, total=747
Spain: min=100, max=100, total=800
Sweden: min=100, max=100, total=800
Turkey: min=100, max=100, total=800
United_Kingdom: min=100, max=100, total=800

In [12]:
print("Countries:", NUMBER_OF_COUNTRIES)
print("Cells:", NUMBER_OF_CELLS)
print("Cell centres:", cell_centres.shape)
print("Cell-country mapping:", cell_to_country.shape)

Countries: 12
Cells: 96
Cell centres: (96, 2)
Cell-country mapping: (96,)

Model Verification

In [13]:
MODEL_NAME = (
    "apple/mobilevitv2-1.0-imagenet1k-256"
)

INPUT_RESOLUTION = 384

processor = AutoImageProcessor.from_pretrained(
    MODEL_NAME,
    size={
        "shortest_edge": INPUT_RESOLUTION,
    },
    crop_size={
        "height": INPUT_RESOLUTION,
        "width": INPUT_RESOLUTION,
    },
)

print("Resize:", processor.size)
print("Crop:", processor.crop_size)

model = AutoModelForImageClassification.from_pretrained(
    MODEL_NAME,
    num_labels=NUMBER_OF_COUNTRIES + NUMBER_OF_CELLS,
    ignore_mismatched_sizes=True,
)

device = torch.device(
    "cuda" if torch.cuda.is_available() else "cpu"
)

model = model.to(device)

print("Device:", device)

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
[transformers] You passed `num_labels=108` which is incompatible to the `id2label` map of length `1000`.

Resize: SizeDict(height=None, width=None, longest_edge=None, shortest_edge=384, max_height=None, max_width=None)
Crop: SizeDict(height=384, width=384, longest_edge=None, shortest_edge=None, max_height=None, max_width=None)

Loading weights: 100%|██████████| 269/269 [00:00<00:00, 43119.61it/s]
[transformers] MobileViTV2ForImageClassification LOAD REPORT from: apple/mobilevitv2-1.0-imagenet1k-256
Key               | Status   |
------------------+----------+--------------------------------------------------------------------------------------------
classifier.bias   | MISMATCH | Reinit due to size mismatch - ckpt: torch.Size([1000]) vs model:torch.Size([108])
classifier.weight | MISMATCH | Reinit due to size mismatch - ckpt: torch.Size([1000, 512]) vs model:torch.Size([108, 512])

Notes:
- MISMATCH:	ckpt weights were loaded, but they did not match the original empty weight shapes.

Device: cuda

In [14]:
total_params = sum(p.numel() for p in model.parameters())

print(f"Parameters: {total_params:,}")
assert total_params <= 5_000_000

Parameters: 4,444,245

Normalizing grid cell centres

In [17]:
normalized_cell_centres = (
    cell_centres.copy()
)

normalized_cell_centres[:, 0] /= 90
normalized_cell_centres[:, 1] /= 180

cell_centres_tensor = torch.tensor(
    normalized_cell_centres,
    dtype=torch.float32,
    device=device,
)

In [18]:
cell_to_country_tensor = torch.tensor(
    cell_to_country,
    dtype=torch.long,
    device=device,
)

In [19]:
print(cell_centres_tensor.shape)
print(cell_to_country_tensor.shape)

torch.Size([96, 2])
torch.Size([96])

Image Processor and Dataset

In [20]:
class GeolocationDataset(Dataset):
    def __init__(
        self,
        dataframe,
        image_dir,
        processor,
        transform=None,
    ):
        self.dataframe = dataframe.reset_index(drop=True)
        self.image_dir = Path(image_dir)
        self.processor = processor
        self.transform = transform

    def __len__(self):
        return len(self.dataframe)

    def __getitem__(self, index):
        row = self.dataframe.iloc[index]

        image_path = self.image_dir / row["filename"]
        image = Image.open(image_path).convert("RGB")

        if self.transform is not None:
            image = self.transform(image)

        pixel_values = self.processor(
            images=image,
            return_tensors="pt",
        )["pixel_values"].squeeze(0)

        coordinates = torch.tensor(
            [
                row["lat"] / 90,
                row["lng"] / 180,
            ],
            dtype=torch.float32,
        )

        country_index = torch.tensor(
            row["country_index"],
            dtype=torch.long,
        )

        cell_index = torch.tensor(
            row["cell_index"],
            dtype=torch.long,
        )

        return (
            pixel_values,
            coordinates,
            country_index,
            cell_index,
        )

In [21]:
train_dataset = GeolocationDataset(
    train_df,
    TRAIN_DIR,
    processor,
    transform=None,
)

val_dataset = GeolocationDataset(
    val_df,
    TRAIN_DIR,
    processor,
    transform=None,
)

In [22]:
BATCH_SIZE = 16

train_loader = DataLoader(
    train_dataset,
    batch_size=BATCH_SIZE,
    shuffle=True,
)

val_loader = DataLoader(
    val_dataset,
    batch_size=BATCH_SIZE,
    shuffle=False,
)

In [23]:
(
    images,
    coordinates,
    country_labels,
    cell_labels,
) = next(iter(train_loader))

images = images.to(device)
coordinates = coordinates.to(device)
country_labels = country_labels.to(device)
cell_labels = cell_labels.to(device)

print("Images:", images.shape)
print("Coordinates:", coordinates.shape)
print("Country labels:", country_labels.shape)
print("Cell labels:", cell_labels.shape)

Images: torch.Size([16, 3, 384, 384])
Coordinates: torch.Size([16, 2])
Country labels: torch.Size([16])
Cell labels: torch.Size([16])

In [24]:
images = images.to(device)

with torch.no_grad():

    test_outputs = model(
        pixel_values=images
    ).logits

print("Outputs:", test_outputs.shape)

Outputs: torch.Size([16, 108])

#Loss and Optimizer

In [25]:
coordinate_loss_function = nn.MSELoss()
country_loss_function = nn.CrossEntropyLoss()
cell_loss_function = nn.CrossEntropyLoss()

COUNTRY_LOSS_WEIGHT = 0.01
CELL_LOSS_WEIGHT = 0.01

optimizer = torch.optim.AdamW(
    model.parameters(),
    lr=1e-4,
)

In [26]:
def haversine_km(lat1, lng1, lat2, lng2):
    radius = 6371.0088

    lat1 = np.radians(lat1)
    lng1 = np.radians(lng1)
    lat2 = np.radians(lat2)
    lng2 = np.radians(lng2)

    difference = (
        np.sin((lat2 - lat1) / 2) ** 2
        + np.cos(lat1)
        * np.cos(lat2)
        * np.sin((lng2 - lng1) / 2) ** 2
    )

    return (
        2
        * radius
        * np.arcsin(
            np.sqrt(np.clip(difference, 0, 1))
        )
    )

In [27]:
train_assigned_centres = cell_centres[
    train_df["cell_index"].to_numpy()
]

train_oracle_distances = haversine_km(
    train_df["lat"].to_numpy(),
    train_df["lng"].to_numpy(),
    train_assigned_centres[:, 0],
    train_assigned_centres[:, 1],
)

val_assigned_centres = cell_centres[
    val_df["cell_index"].to_numpy()
]

val_oracle_distances = haversine_km(
    val_df["lat"].to_numpy(),
    val_df["lng"].to_numpy(),
    val_assigned_centres[:, 0],
    val_assigned_centres[:, 1],
)

print("Training oracle metrics")
print(
    "Mean:",
    np.mean(train_oracle_distances),
)
print(
    "Median:",
    np.median(train_oracle_distances),
)

print("\nValidation oracle metrics")
print(
    "Mean:",
    np.mean(val_oracle_distances),
)
print(
    "Median:",
    np.median(val_oracle_distances),
)

Training oracle metrics
Mean: 88.02578314730059
Median: 80.44632111370835

Validation oracle metrics
Mean: 86.56898861163306
Median: 80.17229427951997

Full Train + Validation Loop

In [26]:
start_epoch = 0
END_EPOCH = 40

history = []

best_median = float("inf")
best_epoch = 0

epochs_without_improvement = 0
patience = 4

for epoch in range(start_epoch, END_EPOCH):

    # --------------------
    # Training
    # --------------------
    model.train()
    total_training_loss = 0

    training_bar = tqdm(
        train_loader,
        desc=f"Epoch {epoch + 1}/{END_EPOCH} - Training",
    )

    for (
        images,
        coordinates,
        country_labels,
        cell_labels,
    ) in training_bar:

        images = images.to(device)
        coordinates = coordinates.to(device)
        country_labels = country_labels.to(device)
        cell_labels = cell_labels.to(device)

        optimizer.zero_grad()

        outputs = model(
            pixel_values=images
        ).logits

        # Split outputs
        country_logits = outputs[
            :, :NUMBER_OF_COUNTRIES
        ]

        cell_logits = outputs[
            :, NUMBER_OF_COUNTRIES:
        ]

        # Convert logits into probabilities
        country_probabilities = torch.softmax(
            country_logits,
            dim=1,
        )

        cell_probabilities = torch.softmax(
            cell_logits,
            dim=1,
        )

        # Give every cell its country's probability
        country_weights_for_cells = country_probabilities[
            :, cell_to_country_tensor
        ]

        # Gate cells using country probabilities
        gated_cell_probabilities = (
            cell_probabilities
            * country_weights_for_cells
        )

        # Make gated probabilities sum to 1
        gated_cell_probabilities = (
            gated_cell_probabilities
            / gated_cell_probabilities.sum(
                dim=1,
                keepdim=True,
            ).clamp_min(1e-8)
        )

        # Weighted average of cell centres
        final_coordinates = (
            gated_cell_probabilities
            @ cell_centres_tensor
        )

        coordinate_loss = coordinate_loss_function(
            final_coordinates,
            coordinates,
        )

        country_loss = country_loss_function(
            country_logits,
            country_labels,
        )

        cell_loss = cell_loss_function(
            cell_logits,
            cell_labels,
        )

        loss = (
            coordinate_loss
            + COUNTRY_LOSS_WEIGHT * country_loss
            + CELL_LOSS_WEIGHT * cell_loss
        )

        loss.backward()
        optimizer.step()

        total_training_loss += loss.item()

        training_bar.set_postfix(
            loss=f"{loss.item():.4f}"
        )

    average_training_loss = (
        total_training_loss / len(train_loader)
    )

    # --------------------
    # Validation
    # --------------------
    model.eval()

    total_validation_loss = 0

    all_predictions = []
    all_coordinates = []

    correct_country_predictions = 0
    correct_cell_predictions = 0
    number_of_validation_images = 0

    validation_bar = tqdm(
        val_loader,
        desc=f"Epoch {epoch + 1}/{END_EPOCH} - Validation",
    )

    with torch.no_grad():

        for (
            images,
            coordinates,
            country_labels,
            cell_labels,
        ) in validation_bar:

            images = images.to(device)
            coordinates = coordinates.to(device)
            country_labels = country_labels.to(device)
            cell_labels = cell_labels.to(device)

            outputs = model(
                pixel_values=images
            ).logits

            # Split outputs
            country_logits = outputs[
                :, :NUMBER_OF_COUNTRIES
            ]

            cell_logits = outputs[
                :, NUMBER_OF_COUNTRIES:
            ]

            # Convert logits into probabilities
            country_probabilities = torch.softmax(
                country_logits,
                dim=1,
            )

            cell_probabilities = torch.softmax(
                cell_logits,
                dim=1,
            )

            # Give every cell its country's probability
            country_weights_for_cells = (
                country_probabilities[
                    :, cell_to_country_tensor
                ]
            )

            # Gate cells using country probabilities
            gated_cell_probabilities = (
                cell_probabilities
                * country_weights_for_cells
            )

            # Make gated probabilities sum to 1
            gated_cell_probabilities = (
                gated_cell_probabilities
                / gated_cell_probabilities.sum(
                    dim=1,
                    keepdim=True,
                ).clamp_min(1e-8)
            )

            # Final coordinate prediction
            final_coordinates = (
                gated_cell_probabilities
                @ cell_centres_tensor
            )

            coordinate_loss = coordinate_loss_function(
                final_coordinates,
                coordinates,
            )

            country_loss = country_loss_function(
                country_logits,
                country_labels,
            )

            cell_loss = cell_loss_function(
                cell_logits,
                cell_labels,
            )

            loss = (
                coordinate_loss
                + COUNTRY_LOSS_WEIGHT * country_loss
                + CELL_LOSS_WEIGHT * cell_loss
            )

            total_validation_loss += loss.item()

            all_predictions.append(
                final_coordinates.cpu().numpy()
            )

            all_coordinates.append(
                coordinates.cpu().numpy()
            )

            predicted_countries = country_logits.argmax(
                dim=1
            )

            predicted_cells = cell_logits.argmax(
                dim=1
            )

            correct_country_predictions += (
                predicted_countries == country_labels
            ).sum().item()

            correct_cell_predictions += (
                predicted_cells == cell_labels
            ).sum().item()

            number_of_validation_images += (
                cell_labels.size(0)
            )

    average_validation_loss = (
        total_validation_loss / len(val_loader)
    )

    country_accuracy = (
        correct_country_predictions
        / number_of_validation_images
    )

    cell_accuracy = (
        correct_cell_predictions
        / number_of_validation_images
    )

    # --------------------
    # Geographic metrics
    # --------------------
    all_predictions = np.concatenate(
        all_predictions
    )

    all_coordinates = np.concatenate(
        all_coordinates
    )

    predictions_degrees = all_predictions.copy()
    coordinates_degrees = all_coordinates.copy()

    predictions_degrees[:, 0] *= 90
    predictions_degrees[:, 1] *= 180

    coordinates_degrees[:, 0] *= 90
    coordinates_degrees[:, 1] *= 180

    distances = haversine_km(
        coordinates_degrees[:, 0],
        coordinates_degrees[:, 1],
        predictions_degrees[:, 0],
        predictions_degrees[:, 1],
    )

    mean_distance = np.mean(distances)
    median_distance = np.median(distances)
    within_200 = np.mean(distances < 200)
    within_750 = np.mean(distances < 750)

    # --------------------
    # Save history
    # --------------------
    history.append({
        "epoch": epoch + 1,
        "training_loss": average_training_loss,
        "validation_loss": average_validation_loss,
        "mean_km": mean_distance,
        "median_km": median_distance,
        "within_200": within_200,
        "within_750": within_750,
        "country_accuracy": country_accuracy,
        "cell_accuracy": cell_accuracy,
    })

    # --------------------
    # Display results
    # --------------------
    print(f"\nEpoch {epoch + 1} results")
    print(f"Training loss: {average_training_loss:.4f}")
    print(f"Validation loss: {average_validation_loss:.4f}")
    print(f"Mean distance: {mean_distance:.1f} km")
    print(f"Median distance: {median_distance:.1f} km")
    print(f"Within 200 km: {within_200:.2%}")
    print(f"Within 750 km: {within_750:.2%}")
    print(f"Country accuracy: {country_accuracy:.2%}")
    print(f"Cell accuracy: {cell_accuracy:.2%}")

    # --------------------
    # Save best model
    # --------------------
    if median_distance < best_median:

        best_median = median_distance
        best_epoch = epoch + 1
        epochs_without_improvement = 0

        torch.save(
            model.state_dict(),
            best_model_path,
        )

        print("Saved new best model.")

    else:

        epochs_without_improvement += 1

        print(
            "Epochs without improvement:",
            epochs_without_improvement,
        )

    # --------------------
    # Save resumable checkpoint
    # --------------------
    torch.save(
        {
            "epoch": epoch + 1,
            "model_state_dict": model.state_dict(),
            "optimizer_state_dict": optimizer.state_dict(),
            "best_median": best_median,
            "best_epoch": best_epoch,
            "history": history,
            "patience": patience,
            "input_resolution": INPUT_RESOLUTION,
            "epochs_without_improvement": (
                epochs_without_improvement
            ),
            "model_name": MODEL_NAME,
            "num_labels": (
                NUMBER_OF_COUNTRIES
                + NUMBER_OF_CELLS
            ),
            "parameter_count": total_params,
            "number_of_countries": (
                NUMBER_OF_COUNTRIES
            ),
            "cells_per_country": (
                CELLS_PER_COUNTRY
            ),
            "cell_construction": (
                "capacity_constrained_kmeans"
            ),

            "number_of_cells": NUMBER_OF_CELLS,
            "cell_centres": (
                cell_centres_tensor
                .detach()
                .cpu()
            ),
            "cell_to_country": (
                cell_to_country_tensor
                .detach()
                .cpu()
            ),
            "country_to_index": country_to_index,
            "index_to_country": index_to_country,
            "country_loss_weight": (
                COUNTRY_LOSS_WEIGHT
            ),
            "cell_loss_weight": (
                CELL_LOSS_WEIGHT
            ),
        },
        checkpoint_path,
    )

    # Preserve history after every epoch
    pd.DataFrame(history).to_csv(
        history_path,
        index=False,
    )

    # --------------------
    # Early stopping
    # --------------------
    if epochs_without_improvement >= patience:
        print("Early stopping.")
        break

Epoch 1/40 - Training: 100%|██████████| 588/588 [02:07<00:00,  4.61it/s, loss=0.0553]
Epoch 1/40 - Validation: 100%|██████████| 147/147 [00:17<00:00,  8.62it/s]

Epoch 1 results
Training loss: 0.0668
Validation loss: 0.0561
Mean distance: 844.2 km
Median distance: 687.0 km
Within 200 km: 12.20%
Within 750 km: 53.83%
Country accuracy: 47.02%
Cell accuracy: 11.82%
Saved new best model.

Epoch 2/40 - Training: 100%|██████████| 588/588 [02:06<00:00,  4.63it/s, loss=0.0435]
Epoch 2/40 - Validation: 100%|██████████| 147/147 [00:16<00:00,  8.72it/s]

Epoch 2 results
Training loss: 0.0513
Validation loss: 0.0469
Mean distance: 689.9 km
Median distance: 496.6 km
Within 200 km: 19.64%
Within 750 km: 67.43%
Country accuracy: 58.84%
Cell accuracy: 17.35%
Saved new best model.

Epoch 3/40 - Training: 100%|██████████| 588/588 [02:07<00:00,  4.60it/s, loss=0.0353]
Epoch 3/40 - Validation: 100%|██████████| 147/147 [00:17<00:00,  8.64it/s]

Epoch 3 results
Training loss: 0.0436
Validation loss: 0.0434
Mean distance: 646.7 km
Median distance: 427.1 km
Within 200 km: 22.58%
Within 750 km: 71.56%
Country accuracy: 62.63%
Cell accuracy: 20.07%
Saved new best model.

Epoch 4/40 - Training: 100%|██████████| 588/588 [02:07<00:00,  4.63it/s, loss=0.0344]
Epoch 4/40 - Validation: 100%|██████████| 147/147 [00:16<00:00,  8.74it/s]

Epoch 4 results
Training loss: 0.0384
Validation loss: 0.0407
Mean distance: 592.0 km
Median distance: 383.7 km
Within 200 km: 25.13%
Within 750 km: 74.57%
Country accuracy: 65.56%
Cell accuracy: 22.24%
Saved new best model.

Epoch 5/40 - Training: 100%|██████████| 588/588 [02:05<00:00,  4.67it/s, loss=0.0388]
Epoch 5/40 - Validation: 100%|██████████| 147/147 [00:16<00:00,  8.81it/s]

Epoch 5 results
Training loss: 0.0340
Validation loss: 0.0396
Mean distance: 581.8 km
Median distance: 362.3 km
Within 200 km: 27.64%
Within 750 km: 75.98%
Country accuracy: 67.52%
Cell accuracy: 25.00%
Saved new best model.

Epoch 6/40 - Training: 100%|██████████| 588/588 [02:06<00:00,  4.66it/s, loss=0.0283]
Epoch 6/40 - Validation: 100%|██████████| 147/147 [00:16<00:00,  8.66it/s]

Epoch 6 results
Training loss: 0.0304
Validation loss: 0.0392
Mean distance: 577.5 km
Median distance: 342.4 km
Within 200 km: 29.85%
Within 750 km: 75.13%
Country accuracy: 68.62%
Cell accuracy: 25.34%
Saved new best model.

Epoch 7/40 - Training: 100%|██████████| 588/588 [02:06<00:00,  4.64it/s, loss=0.0317]
Epoch 7/40 - Validation: 100%|██████████| 147/147 [00:16<00:00,  8.90it/s]

Epoch 7 results
Training loss: 0.0272
Validation loss: 0.0383
Mean distance: 556.8 km
Median distance: 321.7 km
Within 200 km: 31.16%
Within 750 km: 76.57%
Country accuracy: 69.26%
Cell accuracy: 27.13%
Saved new best model.

Epoch 8/40 - Training: 100%|██████████| 588/588 [02:06<00:00,  4.64it/s, loss=0.0234]
Epoch 8/40 - Validation: 100%|██████████| 147/147 [00:17<00:00,  8.64it/s]

Epoch 8 results
Training loss: 0.0245
Validation loss: 0.0390
Mean distance: 574.5 km
Median distance: 324.9 km
Within 200 km: 31.89%
Within 750 km: 74.87%
Country accuracy: 69.01%
Cell accuracy: 28.87%
Epochs without improvement: 1

Epoch 9/40 - Training: 100%|██████████| 588/588 [02:06<00:00,  4.66it/s, loss=0.0176]
Epoch 9/40 - Validation: 100%|██████████| 147/147 [00:16<00:00,  8.84it/s]

Epoch 9 results
Training loss: 0.0219
Validation loss: 0.0386
Mean distance: 544.4 km
Median distance: 297.0 km
Within 200 km: 35.63%
Within 750 km: 76.91%
Country accuracy: 70.62%
Cell accuracy: 30.61%
Saved new best model.

Epoch 10/40 - Training: 100%|██████████| 588/588 [02:02<00:00,  4.79it/s, loss=0.0161]
Epoch 10/40 - Validation: 100%|██████████| 147/147 [00:16<00:00,  8.96it/s]

Epoch 10 results
Training loss: 0.0199
Validation loss: 0.0396
Mean distance: 552.0 km
Median distance: 303.2 km
Within 200 km: 35.67%
Within 750 km: 76.19%
Country accuracy: 69.09%
Cell accuracy: 30.87%
Epochs without improvement: 1

Epoch 11/40 - Training: 100%|██████████| 588/588 [02:02<00:00,  4.81it/s, loss=0.0149]
Epoch 11/40 - Validation: 100%|██████████| 147/147 [00:16<00:00,  9.15it/s]

Epoch 11 results
Training loss: 0.0180
Validation loss: 0.0396
Mean distance: 537.6 km
Median distance: 283.7 km
Within 200 km: 37.24%
Within 750 km: 77.04%
Country accuracy: 70.71%
Cell accuracy: 32.36%
Saved new best model.

Epoch 12/40 - Training: 100%|██████████| 588/588 [02:02<00:00,  4.79it/s, loss=0.0172]
Epoch 12/40 - Validation: 100%|██████████| 147/147 [00:16<00:00,  8.93it/s]

Epoch 12 results
Training loss: 0.0164
Validation loss: 0.0408
Mean distance: 542.0 km
Median distance: 275.2 km
Within 200 km: 38.14%
Within 750 km: 77.00%
Country accuracy: 69.56%
Cell accuracy: 32.78%
Saved new best model.

Epoch 13/40 - Training: 100%|██████████| 588/588 [02:00<00:00,  4.86it/s, loss=0.0141]
Epoch 13/40 - Validation: 100%|██████████| 147/147 [00:16<00:00,  9.02it/s]

Epoch 13 results
Training loss: 0.0149
Validation loss: 0.0415
Mean distance: 536.1 km
Median distance: 268.6 km
Within 200 km: 40.56%
Within 750 km: 76.62%
Country accuracy: 69.90%
Cell accuracy: 33.12%
Saved new best model.

Epoch 14/40 - Training: 100%|██████████| 588/588 [02:04<00:00,  4.73it/s, loss=0.0158]
Epoch 14/40 - Validation: 100%|██████████| 147/147 [00:17<00:00,  8.57it/s]

Epoch 14 results
Training loss: 0.0135
Validation loss: 0.0425
Mean distance: 532.5 km
Median distance: 275.6 km
Within 200 km: 40.43%
Within 750 km: 76.79%
Country accuracy: 70.96%
Cell accuracy: 33.33%
Epochs without improvement: 1

Epoch 15/40 - Training: 100%|██████████| 588/588 [02:06<00:00,  4.66it/s, loss=0.0157]
Epoch 15/40 - Validation: 100%|██████████| 147/147 [00:16<00:00,  8.75it/s]

Epoch 15 results
Training loss: 0.0123
Validation loss: 0.0428
Mean distance: 525.1 km
Median distance: 262.5 km
Within 200 km: 42.01%
Within 750 km: 77.13%
Country accuracy: 70.79%
Cell accuracy: 34.10%
Saved new best model.

Epoch 16/40 - Training: 100%|██████████| 588/588 [02:06<00:00,  4.64it/s, loss=0.0100]
Epoch 16/40 - Validation: 100%|██████████| 147/147 [00:17<00:00,  8.58it/s]

Epoch 16 results
Training loss: 0.0111
Validation loss: 0.0442
Mean distance: 524.5 km
Median distance: 252.3 km
Within 200 km: 42.69%
Within 750 km: 77.00%
Country accuracy: 71.26%
Cell accuracy: 34.23%
Saved new best model.

Epoch 17/40 - Training: 100%|██████████| 588/588 [02:06<00:00,  4.66it/s, loss=0.0073]
Epoch 17/40 - Validation: 100%|██████████| 147/147 [00:16<00:00,  8.71it/s]

Epoch 17 results
Training loss: 0.0100
Validation loss: 0.0442
Mean distance: 520.0 km
Median distance: 254.9 km
Within 200 km: 43.58%
Within 750 km: 77.64%
Country accuracy: 70.49%
Cell accuracy: 35.42%
Epochs without improvement: 1

Epoch 18/40 - Training: 100%|██████████| 588/588 [02:05<00:00,  4.67it/s, loss=0.0076]
Epoch 18/40 - Validation: 100%|██████████| 147/147 [00:16<00:00,  9.03it/s]

Epoch 18 results
Training loss: 0.0089
Validation loss: 0.0456
Mean distance: 526.6 km
Median distance: 252.3 km
Within 200 km: 42.73%
Within 750 km: 77.55%
Country accuracy: 70.49%
Cell accuracy: 35.08%
Saved new best model.

Epoch 19/40 - Training: 100%|██████████| 588/588 [02:05<00:00,  4.67it/s, loss=0.0094]
Epoch 19/40 - Validation: 100%|██████████| 147/147 [00:16<00:00,  8.95it/s]

Epoch 19 results
Training loss: 0.0080
Validation loss: 0.0470
Mean distance: 535.1 km
Median distance: 259.4 km
Within 200 km: 42.81%
Within 750 km: 76.66%
Country accuracy: 69.98%
Cell accuracy: 35.12%
Epochs without improvement: 1

Epoch 20/40 - Training: 100%|██████████| 588/588 [02:04<00:00,  4.73it/s, loss=0.0090]
Epoch 20/40 - Validation: 100%|██████████| 147/147 [00:16<00:00,  8.99it/s]

Epoch 20 results
Training loss: 0.0071
Validation loss: 0.0491
Mean distance: 532.0 km
Median distance: 255.6 km
Within 200 km: 43.24%
Within 750 km: 76.36%
Country accuracy: 69.73%
Cell accuracy: 34.91%
Epochs without improvement: 2

Epoch 21/40 - Training: 100%|██████████| 588/588 [02:04<00:00,  4.74it/s, loss=0.0058]
Epoch 21/40 - Validation: 100%|██████████| 147/147 [00:16<00:00,  8.89it/s]

Epoch 21 results
Training loss: 0.0063
Validation loss: 0.0480
Mean distance: 530.6 km
Median distance: 252.0 km
Within 200 km: 43.75%
Within 750 km: 76.57%
Country accuracy: 70.32%
Cell accuracy: 35.16%
Saved new best model.

Epoch 22/40 - Training: 100%|██████████| 588/588 [02:03<00:00,  4.76it/s, loss=0.0071]
Epoch 22/40 - Validation: 100%|██████████| 147/147 [00:16<00:00,  9.04it/s]

Epoch 22 results
Training loss: 0.0053
Validation loss: 0.0516
Mean distance: 544.5 km
Median distance: 261.7 km
Within 200 km: 43.24%
Within 750 km: 76.06%
Country accuracy: 69.69%
Cell accuracy: 35.03%
Epochs without improvement: 1

Epoch 23/40 - Training: 100%|██████████| 588/588 [02:03<00:00,  4.75it/s, loss=0.0037]
Epoch 23/40 - Validation: 100%|██████████| 147/147 [00:16<00:00,  8.74it/s]

Epoch 23 results
Training loss: 0.0049
Validation loss: 0.0499
Mean distance: 525.6 km
Median distance: 243.6 km
Within 200 km: 44.43%
Within 750 km: 77.34%
Country accuracy: 71.05%
Cell accuracy: 35.67%
Saved new best model.

Epoch 24/40 - Training: 100%|██████████| 588/588 [02:04<00:00,  4.73it/s, loss=0.0053]
Epoch 24/40 - Validation: 100%|██████████| 147/147 [00:18<00:00,  7.83it/s]

Epoch 24 results
Training loss: 0.0041
Validation loss: 0.0519
Mean distance: 534.6 km
Median distance: 250.4 km
Within 200 km: 44.47%
Within 750 km: 76.45%
Country accuracy: 70.37%
Cell accuracy: 36.14%
Epochs without improvement: 1

Epoch 25/40 - Training: 100%|██████████| 588/588 [02:08<00:00,  4.56it/s, loss=0.0034]
Epoch 25/40 - Validation: 100%|██████████| 147/147 [00:16<00:00,  8.75it/s]

Epoch 25 results
Training loss: 0.0035
Validation loss: 0.0522
Mean distance: 533.6 km
Median distance: 245.6 km
Within 200 km: 44.60%
Within 750 km: 77.17%
Country accuracy: 70.66%
Cell accuracy: 35.84%
Epochs without improvement: 2

Epoch 26/40 - Training: 100%|██████████| 588/588 [02:05<00:00,  4.69it/s, loss=0.0028]
Epoch 26/40 - Validation: 100%|██████████| 147/147 [00:16<00:00,  8.79it/s]

Epoch 26 results
Training loss: 0.0029
Validation loss: 0.0539
Mean distance: 529.4 km
Median distance: 240.6 km
Within 200 km: 45.75%
Within 750 km: 76.49%
Country accuracy: 70.37%
Cell accuracy: 36.82%
Saved new best model.

Epoch 27/40 - Training: 100%|██████████| 588/588 [02:04<00:00,  4.73it/s, loss=0.0035]
Epoch 27/40 - Validation: 100%|██████████| 147/147 [00:16<00:00,  8.85it/s]

Epoch 27 results
Training loss: 0.0026
Validation loss: 0.0554
Mean distance: 514.7 km
Median distance: 247.5 km
Within 200 km: 44.77%
Within 750 km: 77.68%
Country accuracy: 71.30%
Cell accuracy: 36.86%
Epochs without improvement: 1

Epoch 28/40 - Training: 100%|██████████| 588/588 [02:04<00:00,  4.74it/s, loss=0.0055]
Epoch 28/40 - Validation: 100%|██████████| 147/147 [00:16<00:00,  8.90it/s]

Epoch 28 results
Training loss: 0.0025
Validation loss: 0.0583
Mean distance: 547.5 km
Median distance: 266.7 km
Within 200 km: 43.41%
Within 750 km: 75.30%
Country accuracy: 68.58%
Cell accuracy: 35.46%
Epochs without improvement: 2

Epoch 29/40 - Training: 100%|██████████| 588/588 [02:04<00:00,  4.70it/s, loss=0.0036]
Epoch 29/40 - Validation: 100%|██████████| 147/147 [00:16<00:00,  9.00it/s]

Epoch 29 results
Training loss: 0.0025
Validation loss: 0.0574
Mean distance: 530.0 km
Median distance: 245.6 km
Within 200 km: 44.69%
Within 750 km: 76.57%
Country accuracy: 70.32%
Cell accuracy: 36.69%
Epochs without improvement: 3

Epoch 30/40 - Training: 100%|██████████| 588/588 [02:03<00:00,  4.76it/s, loss=0.0026]
Epoch 30/40 - Validation: 100%|██████████| 147/147 [00:16<00:00,  8.67it/s]

Epoch 30 results
Training loss: 0.0019
Validation loss: 0.0579
Mean distance: 531.1 km
Median distance: 239.7 km
Within 200 km: 44.90%
Within 750 km: 76.49%
Country accuracy: 70.75%
Cell accuracy: 36.82%
Saved new best model.

Epoch 31/40 - Training: 100%|██████████| 588/588 [02:05<00:00,  4.70it/s, loss=0.0062]
Epoch 31/40 - Validation: 100%|██████████| 147/147 [00:16<00:00,  8.99it/s]

Epoch 31 results
Training loss: 0.0017
Validation loss: 0.0579
Mean distance: 535.7 km
Median distance: 241.9 km
Within 200 km: 45.20%
Within 750 km: 76.19%
Country accuracy: 70.45%
Cell accuracy: 36.01%
Epochs without improvement: 1

Epoch 32/40 - Training: 100%|██████████| 588/588 [02:03<00:00,  4.77it/s, loss=0.0016]
Epoch 32/40 - Validation: 100%|██████████| 147/147 [00:16<00:00,  8.81it/s]

Epoch 32 results
Training loss: 0.0018
Validation loss: 0.0595
Mean distance: 522.0 km
Median distance: 246.2 km
Within 200 km: 45.58%
Within 750 km: 76.28%
Country accuracy: 70.83%
Cell accuracy: 36.69%
Epochs without improvement: 2

Epoch 33/40 - Training: 100%|██████████| 588/588 [02:05<00:00,  4.68it/s, loss=0.0057]
Epoch 33/40 - Validation: 100%|██████████| 147/147 [00:17<00:00,  8.53it/s]

Epoch 33 results
Training loss: 0.0015
Validation loss: 0.0593
Mean distance: 528.8 km
Median distance: 233.5 km
Within 200 km: 46.00%
Within 750 km: 76.19%
Country accuracy: 70.41%
Cell accuracy: 37.71%
Saved new best model.

Epoch 34/40 - Training: 100%|██████████| 588/588 [02:06<00:00,  4.63it/s, loss=0.0057]
Epoch 34/40 - Validation: 100%|██████████| 147/147 [00:16<00:00,  8.65it/s]

Epoch 34 results
Training loss: 0.0015
Validation loss: 0.0594
Mean distance: 525.8 km
Median distance: 246.4 km
Within 200 km: 44.98%
Within 750 km: 76.87%
Country accuracy: 71.30%
Cell accuracy: 36.90%
Epochs without improvement: 1

Epoch 35/40 - Training: 100%|██████████| 588/588 [02:04<00:00,  4.73it/s, loss=0.0019]
Epoch 35/40 - Validation: 100%|██████████| 147/147 [00:17<00:00,  8.44it/s]

Epoch 35 results
Training loss: 0.0015
Validation loss: 0.0607
Mean distance: 517.3 km
Median distance: 240.6 km
Within 200 km: 45.15%
Within 750 km: 76.49%
Country accuracy: 71.05%
Cell accuracy: 37.03%
Epochs without improvement: 2

Epoch 36/40 - Training: 100%|██████████| 588/588 [02:05<00:00,  4.69it/s, loss=0.0030]
Epoch 36/40 - Validation: 100%|██████████| 147/147 [00:16<00:00,  9.01it/s]

Epoch 36 results
Training loss: 0.0013
Validation loss: 0.0604
Mean distance: 526.4 km
Median distance: 243.1 km
Within 200 km: 45.88%
Within 750 km: 76.79%
Country accuracy: 71.85%
Cell accuracy: 37.20%
Epochs without improvement: 3

Epoch 37/40 - Training: 100%|██████████| 588/588 [02:05<00:00,  4.70it/s, loss=0.0007]
Epoch 37/40 - Validation: 100%|██████████| 147/147 [00:16<00:00,  8.90it/s]

Epoch 37 results
Training loss: 0.0012
Validation loss: 0.0618
Mean distance: 520.0 km
Median distance: 234.1 km
Within 200 km: 45.49%
Within 750 km: 76.79%
Country accuracy: 71.47%
Cell accuracy: 37.54%
Epochs without improvement: 4
Early stopping.

In [15]:
best_weights = torch.load(
    best_model_path,
    map_location=device,
    weights_only=True,
)

model.load_state_dict(best_weights)
model.eval()

print("Loaded epoch-33 best model.")
print("Input resolution:", INPUT_RESOLUTION)

Loaded epoch-33 best model.
Input resolution: 384

In [28]:
all_country_logits = []
all_cell_logits = []
all_coordinates = []
all_country_labels = []

model.eval()

with torch.inference_mode():

    for (
        images,
        coordinates,
        country_labels,
        _,
    ) in tqdm(
        val_loader,
        desc="Collecting validation logits",
    ):

        images = images.to(device)

        outputs = model(
            pixel_values=images
        ).logits

        country_logits = outputs[
            :, :NUMBER_OF_COUNTRIES
        ]

        cell_logits = outputs[
            :, NUMBER_OF_COUNTRIES:
        ]

        all_country_logits.append(
            country_logits.cpu()
        )

        all_cell_logits.append(
            cell_logits.cpu()
        )

        all_coordinates.append(coordinates)
        all_country_labels.append(
            country_labels
        )

Collecting validation logits: 100%|██████████| 147/147 [00:45<00:00,  3.20it/s]

In [29]:
all_country_logits = torch.cat(
    all_country_logits
)

all_cell_logits = torch.cat(
    all_cell_logits
)

all_coordinates = torch.cat(
    all_coordinates
)

all_country_labels = torch.cat(
    all_country_labels
)

evaluation_cell_to_country = (
    cell_to_country_tensor.detach().cpu()
)

evaluation_cell_centres = (
    cell_centres_tensor.detach().cpu()
)

In [30]:
evaluation_cell_to_country = (
    cell_to_country_tensor
    .detach()
    .cpu()
)

evaluation_cell_centres = (
    cell_centres_tensor
    .detach()
    .cpu()
)

print(
    all_country_logits.device,
    evaluation_cell_to_country.device,
    evaluation_cell_centres.device,
)

cpu cpu cpu

In [31]:
def evaluate_configuration(
    name,
    country_temperature=1.0,
    cell_temperature=1.0,
    use_country_gating=True,
):

    country_probabilities = torch.softmax(
        all_country_logits
        / country_temperature,
        dim=1,
    )

    cell_probabilities = torch.softmax(
        all_cell_logits
        / cell_temperature,
        dim=1,
    )

    if use_country_gating:

        country_weights_for_cells = (
            country_probabilities[
                :, evaluation_cell_to_country
            ]
        )

        final_cell_probabilities = (
            cell_probabilities
            * country_weights_for_cells
        )

        final_cell_probabilities = (
            final_cell_probabilities
            / final_cell_probabilities.sum(
                dim=1,
                keepdim=True,
            ).clamp_min(1e-8)
        )

    else:

        final_cell_probabilities = (
            cell_probabilities
        )

    predicted_coordinates = (
        final_cell_probabilities
        @ evaluation_cell_centres
    )

    predictions_degrees = (
        predicted_coordinates.numpy().copy()
    )

    coordinates_degrees = (
        all_coordinates.numpy().copy()
    )

    predictions_degrees[:, 0] *= 90
    predictions_degrees[:, 1] *= 180

    coordinates_degrees[:, 0] *= 90
    coordinates_degrees[:, 1] *= 180

    distances = haversine_km(
        coordinates_degrees[:, 0],
        coordinates_degrees[:, 1],
        predictions_degrees[:, 0],
        predictions_degrees[:, 1],
    )

    return {
        "configuration": name,
        "country_temperature": (
            country_temperature
        ),
        "cell_temperature": (
            cell_temperature
        ),
        "country_gating": (
            use_country_gating
        ),
        "mean_km": np.mean(distances),
        "median_km": np.median(distances),
        "within_200": np.mean(
            distances < 200
        ),
        "within_750": np.mean(
            distances < 750
        ),
    }

In [32]:
predicted_countries = (
    all_country_logits.argmax(dim=1)
)

country_accuracy = (
    predicted_countries
    == all_country_labels
).float().mean().item()

print(
    f"Country accuracy: "
    f"{country_accuracy:.2%}"
)

Country accuracy: 70.41%

In [33]:
temperature_values = [
    0.25,
    0.50,
    0.75,
    1.00,
    1.25,
    1.50,
    2.00,
]

temperature_results = []

In [34]:
for country_temperature in temperature_values:

    for cell_temperature in temperature_values:

        result = evaluate_configuration(
            name="Country gating",
            country_temperature=(
                country_temperature
            ),
            cell_temperature=(
                cell_temperature
            ),
            use_country_gating=True,
        )

        temperature_results.append(result)

In [35]:
for cell_temperature in temperature_values:

    result = evaluate_configuration(
        name="No country gating",
        country_temperature=1.0,
        cell_temperature=(
            cell_temperature
        ),
        use_country_gating=False,
    )

    temperature_results.append(result)

In [37]:
temperature_results_df = pd.DataFrame(
    temperature_results
)

temperature_results_df = (
    temperature_results_df
    .sort_values(
        by=[
            "median_km",
            "mean_km",
        ]
    )
    .reset_index(drop=True)
)

display(
    temperature_results_df.head(15)
)

temperature_results_df.to_csv(
    #results_path,
    index=False,
)

,configuration,country_temperature,cell_temperature,country_gating,mean_km,median_km,within_200,within_750
0,Country gating,0.25,1.25,True,544.949219,224.608688,0.466412,0.756378
1,Country gating,0.25,1.00,True,544.279358,225.015503,0.467687,0.758078
2,Country gating,0.25,1.50,True,546.096130,225.503082,0.460459,0.755527
3,Country gating,0.25,0.50,True,542.940918,225.895447,0.466837,0.755102
4,Country gating,0.25,0.75,True,543.818420,226.834167,0.469388,0.756803
5,Country gating,0.50,1.25,True,536.244385,227.744843,0.461735,0.760204
6,Country gating,0.50,1.00,True,535.207153,228.132660,0.465136,0.761905
7,Country gating,0.50,0.75,True,535.190857,228.454834,0.465561,0.759354
8,Country gating,0.50,1.50,True,537.686157,228.752716,0.454082,0.758503
9,Country gating,0.50,0.25,True,545.038147,229.150391,0.463010,0.752551
10,Country gating,0.75,0.75,True,532.421692,229.151459,0.463861,0.759354
11,Country gating,0.50,0.50,True,537.457031,230.004807,0.464711,0.754677
12,Country gating,1.00,0.75,True,531.323547,230.467590,0.462585,0.757653
13,Country gating,0.25,0.25,True,543.935608,230.755096,0.460884,0.751701
14,Country gating,0.75,0.50,True,536.541443,231.263916,0.463861,0.755102

'configuration,country_temperature,cell_temperature,country_gating,mean_km,median_km,within_200,within_750\nCountry gating,0.25,1.25,True,544.9492,224.60869,0.4664115646258503,0.7563775510204082\nCountry gating,0.25,1.0,True,544.27936,225.0155,0.467687074829932,0.7580782312925171\nCountry gating,0.25,1.5,True,546.0961,225.50308,0.4604591836734694,0.7555272108843537\nCountry gating,0.25,0.5,True,542.9409,225.89545,0.46683673469387754,0.7551020408163265\nCountry gating,0.25,0.75,True,543.8184,226.83417,0.46938775510204084,0.7568027210884354\nCountry gating,0.5,1.25,True,536.2444,227.74484,0.461734693877551,0.7602040816326531\nCountry gating,0.5,1.0,True,535.20715,228.13266,0.4651360544217687,0.7619047619047619\nCountry gating,0.5,0.75,True,535.19086,228.45483,0.4655612244897959,0.7593537414965986\nCountry gating,0.5,1.5,True,537.68616,228.75272,0.45408163265306123,0.7585034013605442\nCountry gating,0.5,0.25,True,545.03815,229.15039,0.4630102040816326,0.7525510204081632\nCountry gating,0.75,0.75,True,532.4217,229.15146,0.4638605442176871,0.7593537414965986\nCountry gating,0.5,0.5,True,537.45703,230.0048,0.46471088435374147,0.7546768707482994\nCountry gating,1.0,0.75,True,531.32355,230.46759,0.46258503401360546,0.7576530612244898\nCountry gating,0.25,0.25,True,543.9356,230.7551,0.4608843537414966,0.7517006802721088\nCountry gating,0.75,0.5,True,536.54144,231.26392,0.4638605442176871,0.7551020408163265\nCountry gating,1.0,0.5,True,537.28705,231.26392,0.4638605442176871,0.7563775510204082\nCountry gating,0.75,1.25,True,531.01904,231.27577,0.4574829931972789,0.7653061224489796\nCountry gating,1.25,0.75,True,531.02295,231.67883,0.46003401360544216,0.7593537414965986\nCountry gating,1.5,0.5,True,539.5437,231.96469,0.4604591836734694,0.7546768707482994\nCountry gating,1.25,0.5,True,538.462,232.11703,0.46343537414965985,0.7559523809523809\nCountry gating,0.75,1.0,True,530.86066,232.21735,0.4608843537414966,0.7614795918367347\nCountry gating,0.25,2.0,True,549.6667,232.32826,0.4494047619047619,0.7568027210884354\nCountry gating,0.75,0.25,True,548.9261,232.38742,0.4608843537414966,0.7529761904761905\nCountry gating,1.5,0.75,True,531.1322,232.76575,0.4604591836734694,0.7589285714285714\nCountry gating,0.75,1.5,True,532.1128,232.85817,0.4481292517006803,0.764030612244898\nCountry gating,1.0,1.0,True,528.7707,233.54486,0.46003401360544216,0.7619047619047619\nCountry gating,1.25,1.0,True,527.53436,233.88281,0.4604591836734694,0.7614795918367347\nCountry gating,2.0,0.25,True,554.0783,233.97992,0.4583333333333333,0.7482993197278912\nCountry gating,1.25,0.25,True,552.82367,234.40833,0.45918367346938777,0.75\nCountry gating,1.5,0.25,True,553.4146,234.40852,0.45790816326530615,0.7487244897959183\nCountry gating,1.0,0.25,True,551.56757,235.11287,0.45918367346938777,0.752125850340136\nCountry gating,1.5,1.0,True,526.8304,235.12646,0.4570578231292517,0.7610544217687075\nCountry gating,2.0,0.5,True,540.9275,237.18317,0.459608843537415,0.7529761904761905\nCountry gating,1.25,1.25,True,526.1466,237.67035,0.4494047619047619,0.764030612244898\nCountry gating,1.0,1.25,True,528.05444,237.70563,0.45110544217687076,0.7657312925170068\nCountry gating,2.0,0.75,True,531.6373,237.85535,0.45535714285714285,0.7580782312925171\nCountry gating,1.5,1.25,True,524.8043,238.37561,0.44855442176870747,0.7644557823129252\nCountry gating,2.0,1.0,True,526.1476,239.16512,0.4557823129251701,0.7623299319727891\nCountry gating,1.0,1.5,True,528.55273,239.20671,0.4443027210884354,0.7653061224489796\nCountry gating,0.5,2.0,True,541.7902,239.2142,0.4417517006802721,0.7580782312925171\nNo country gating,1.0,0.5,False,543.41284,239.8804,0.45408163265306123,0.7517006802721088\nCountry gating,2.0,1.25,True,523.2171,239.89835,0.4494047619047619,0.7644557823129252\nNo country gating,1.0,0.25,False,555.5894,240.32205,0.4549319727891156,0.747874149659864\nCountry gating,1.25,1.5,True,526.1577,241.59558,0.44387755102040816,0.764030612244898\nCountry gating,1.5,1.5,True,524.4229,245.12091,0.44260204081632654,0.7627551020408163\nCountry gating,0.75,2.0,True,536.0282,246.47827,0.43920068027210885,0.7623299319727891\nCountry gating,2.0,1.5,True,522.16345,247.36682,0.44387755102040816,0.7657312925170068\nCountry gating,1.0,2.0,True,531.9279,251.63281,0.43452380952380953,0.7644557823129252\nCountry gating,1.25,2.0,True,528.8945,252.9061,0.43239795918367346,0.7653061224489796\nNo country gating,1.0,0.75,False,533.96515,254.29077,0.4451530612244898,0.7572278911564626\nCountry gating,1.5,2.0,True,526.64056,256.8429,0.43112244897959184,0.7619047619047619\nCountry gating,2.0,2.0,True,523.6373,264.13684,0.4268707482993197,0.7653061224489796\nNo country gating,1.0,1.0,False,527.33374,266.66248,0.4332482993197279,0.7593537414965986\nNo country gating,1.0,1.25,False,525.1488,282.89716,0.421343537414966,0.7614795918367347\nNo country gating,1.0,1.5,False,530.5479,307.18542,0.3826530612244898,0.7602040816326531\nNo country gating,1.0,2.0,False,575.9315,389.34305,0.25977891156462585,0.7334183673469388\n'

In [38]:
best_gated_result = (
    temperature_results_df[
        temperature_results_df[
            "country_gating"
        ]
    ]
    .iloc[0]
)

best_ungated_result = (
    temperature_results_df[
        ~temperature_results_df[
            "country_gating"
        ]
    ]
    .iloc[0]
)

display(
    pd.DataFrame([
        best_gated_result,
        best_ungated_result,
    ])
)

,configuration,country_temperature,cell_temperature,country_gating,mean_km,median_km,within_200,within_750
0,Country gating,0.25,1.25,True,544.949219,224.608688,0.466412,0.756378
40,No country gating,1.00,0.50,False,543.412842,239.880402,0.454082,0.751701

In [39]:
BEST_COUNTRY_TEMPERATURE = 0.25
BEST_CELL_TEMPERATURE = 1.25

best_configuration = (
    temperature_results_df[
        (
            temperature_results_df[
                "country_temperature"
            ]
            == BEST_COUNTRY_TEMPERATURE
        )
        &
        (
            temperature_results_df[
                "cell_temperature"
            ]
            == BEST_CELL_TEMPERATURE
        )
        &
        (
            temperature_results_df[
                "country_gating"
            ]
        )
    ]
    .copy()
)

best_configuration.to_csv(
    OUTPUT_DIR / "best_configuration.csv",
    index=False,
)